# Server
server.port=8080

# Application Name
spring.application.name=write_prompt

# MySQL DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/write_prompt?serverTimezone=UTC
spring.datasource.username=ssafy
spring.datasource.password=ssafy

# MyBatis
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.ssafy.wp.model.dto
mybatis.configuration.map-underscore-to-camel-case=true

# Swagger / SpringDoc
springdoc.packages-to-scan=com.ssafy.wp.controller
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
